development:
  adapter: postgresql
  database: uploadbox_development
  host: localhost

test:
  adapter: postgresql
  database: uploadbox_test
  host: localhost

production:
  adapter: postgresql
  database: uploadbox_production
  host: localhost
